[workspace]
members = [
    "vespe-buzz", "vespe-cli",
    "vespe-tui",
]

[package]
name = "vespe"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ollama_test_client"
path = "src/bin/ollama_test_client.rs"

[[bin]]
name = "ollama_agent_client"
path = "src/bin/ollama_agent_client.rs"

[[bin]]
name = "data-generator"
path = "src/bin/data_generator/main.rs"

[[bin]]
name = "tool-format-tester"
path = "src/bin/tool-format-tester/main.rs"

[[bin]]
name = "test_task_api"
path = "src/bin/test_task_api.rs"


[dependencies]
rand = "0.8"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
clap = { version = "4", features = ["derive"] }
anyhow = "1"
thiserror = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
reqwest = { version = "0.12", features = ["json", "rustls-tls", "blocking"] }
async-trait = "0.1"
llm = "1.3.4"
chrono = "0.4"
handlebars = "5.1.0"
tracing-appender = "0.2"
regex = "1.10.0"
once_cell = "1.19.0"
serde-xml-rs = "0.6"
tokio-stream = "0.1"
futures-util = "0.3"
tempfile = "3.22"
